#!/usr/bin/env bash
# Block edits to docs/ — it is Vite build output (emptyOutDir: true) and
# any manual edits are wiped on the next `npm run build`.
set -euo pipefail

path="$(jq -r '.tool_input.file_path // empty')"

case "$path" in
  docs|docs/*|*/docs|*/docs/*)
    echo "Refusing to edit ${path}: docs/ is generated by 'npm run build' (emptyOutDir wipes hand edits). Update the source under src/ or public/ instead." >&2
    exit 2
    ;;
esac
exit 0
